### ISSUE TITLE
Why are you pushing to master?

### ISSUE THREAD

**Issue by tindleaj** [cahweb/studio-cpt#1]
Please.

**Comment by veech** [comment]
Because I wanted to have something there before starting to work in the dev branch. I'll just do it there from now on

**Comment by tindleaj** [comment]
Don't be such a scrub.

**Comment by veech** [comment]
They didn't mention this issue in semantic version naming rev10 bet26. But you're right. I'm a scrub. I'm sorry.

**Comment by tindleaj** [comment]
I'm going to semantic version the side of your head with my hand.

**Comment by veech** [comment]
Unfortunately I am mistaken, and I understand you are right. You are always right Austin, I shouldn't ever disagree with you.

**Comment by tindleaj** [comment]
Thank you for that, I know I am.
